### ISSUE TITLE
/usr/include/c++/7/mutex:542:44: error: macro "lock" passed 3 arguments, but takes just 1      lock(_L1& __l1, _L2& __l2, _L3&... __l3)

### ISSUE THREAD

**Issue by bryantaoli** [shaolinbit/RTKinGSS#1]
Thank you to share your code. But if I compile the code, it shows the error: "/usr/include/c++/7/mutex:542:44: error: macro "lock" passed 3 arguments, but takes just 1
     lock(_L1& __l1, _L2& __l2, _L3&... __l3)". How can I deal with it?

**Comment by shaolinbit** [comment]
We have met this problem. It is easy to be solved. It looks like your rtklib library contradicts with the mutex library.  In that library, lock means the thread lock while in rtklib it means a satellite status. For this reason, you should solve this problem by yourself. Change the lock function name "lock" in RTKinGSS to "GSS_lock" or something else what you wanna. We changed it and made it pass in some computers.
